# Generated by Django 3.1.6 on 2021-02-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ans',
            field=models.CharField(max_length=255),
        ),
    ]
