# Generated by Django 3.1.6 on 2021-02-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20210209_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='q',
        ),
    ]
